apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: github-tests-dotnet-basic-zzaxuvrm
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: github-tests-dotnet-basic-zzaxuvrm 
  name: github-tests-dotnet-basic-zzaxuvrm
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: github-tests-dotnet-basic-zzaxuvrm 
